// Generate web/js/icons.js from Phosphor Icons (MIT, https://phosphoricons.com).
//   npm run icons
// Filled weights for the tab bar (as Apple's tab bars prefer), regular for controls.

import { readFileSync, writeFileSync } from "node:fs";

const PICK = {
  sky: ["moon-stars", "fill"],
  launches: ["rocket-launch", "fill"],
  flights: ["globe-hemisphere-east", "fill"],
  digest: ["newspaper", "fill"],
  alerts: ["bell", "fill"],
  location: ["navigation-arrow", "fill"],
  layers: ["stack", "regular"],
  clock: ["clock", "regular"],
  play: ["play", "fill"],
  pause: ["pause", "fill"],
  back: ["clock-counter-clockwise", "regular"],
  chevronRight: ["caret-right", "bold"],
  chevronLeft: ["caret-left", "bold"],
  close: ["x", "bold"],
  calendar: ["calendar-plus", "regular"],
  search: ["magnifying-glass", "regular"],
  check: ["check", "bold"],
  copy: ["copy", "regular"],
  external: ["arrow-square-out", "regular"],
  info: ["info", "regular"],
  eye: ["eye", "regular"],
  rocket: ["rocket", "fill"],
  star: ["star-four", "fill"],
  telegram: ["telegram-logo", "regular"],
  rss: ["rss-simple", "regular"],
  crosshair: ["crosshair", "regular"],
  globe: ["globe-hemisphere-east", "regular"],
  moon: ["moon-stars", "regular"],
};

const root = new URL("../node_modules/@phosphor-icons/core/assets/", import.meta.url);
const lines = [
  "// Generated by scripts/build-icons.mjs from Phosphor Icons (MIT License,",
  "// Copyright (c) 2023 Phosphor Icons, https://github.com/phosphor-icons/core). Do not edit.",
  "",
  "const svg = (body) =>",
  "  `<svg class=\"icon\" viewBox=\"0 0 256 256\" fill=\"currentColor\" aria-hidden=\"true\" focusable=\"false\">${body}</svg>`;",
  "",
  "export const icons = {",
];
for (const [key, [name, weight]] of Object.entries(PICK)) {
  const file = weight === "regular" ? `${weight}/${name}.svg` : `${weight}/${name}-${weight}.svg`;
  const text = readFileSync(new URL(file, root), "utf8");
  const body = text.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();
  lines.push(`  ${key}: svg(${JSON.stringify(body)}),`);
}
lines.push("};", "");
writeFileSync(new URL("../web/js/icons.js", import.meta.url), lines.join("\n"));
console.log(`wrote ${Object.keys(PICK).length} icons`);
